version: '3'
services:
    middleware:
        build: ./middleware
        container_name: middleware
        ports:
            - "8080:8080"
        volumes:
            - ./middleware/logs/:/usr/local/tomcat/logs/
        restart: on-failure
    capture:
        build: ./capture
        container_name: capture
        restart: on-failure
        volumes: 
            - ./capture/drools/:/usr/local/tomcat/webapps/capturingapp-0.1.1/WEB-INF/classes/drools/
        depends_on: 
            - epcis
    epcis:
        build: ./epcis
        container_name: epcis
        ports: 
            - "4080:8080"
        restart: always
        depends_on:
            - epcis-db
    epcis-adapter:
        build: ./epcis-adapter
        container_name: epcis-adapter
        restart: always
    epcis-db:
        container_name: epcis-db
        image: cloud4things/fosstrak_db
        volumes: 
            - ./epcis-db/data/:/var/lib/mysql
        restart: always
    web:
        container_name: web
        build: ./web
        restart: always
    proxy:
        image: nginx:latest
        container_name: proxy
        ports:
        - "3000:80"
        volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
            - epcis-adapter