version: '3'
services:
    # Middleware
    middleware:
        build: ./middleware
        container_name: middleware
        ports:
            - "8080:8080"
        volumes:
            - ./middleware/logs/:/usr/local/tomcat/logs/
        restart: on-failure
    # EPCIS Repository + EPCIS SQL database
    # Capture application
    # Query application