version: '3'
services:
    middleware:
        build: ./middleware
        container_name: middleware
        ports:
            - "8080:8080"
        volumes:
            - ./middleware/logs/:/usr/local/tomcat/logs/
        restart: on-failure
    epcis:
        build: ./epcis
        container_name: epcis
        ports: 
            - "4080:8080"
        volumes:
            - ./epcis/logs/:/usr/local/tomcat/logs/
        depends_on:
            - epcisdb
    epcisdb:
        image: mysql
        container_name: epcisdb
        volumes: 
            - ./epcisdb/data/:/var/lib/mysql
            - ./epcisdb/epcis_schema.sql:/docker-entrypoint-initdb.d/epcis_schema.sql
        environment:
            - MYSQL_ROOT_PASSWORD=epcis
            - MYSQL_DATABASE=epcis
            - MYSQL_USER=epcis 
            - MYSQL_PASSWORD=epcis
        restart: always
    adminer:
        image: adminer
        restart: always
        ports:
            - "8081:8080"